version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  elastic:
    image: elasticsearch:8.15.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"

  kibana:
    image: kibana:8.15.2
    container_name: kibana
    depends_on:
      - elastic
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic:9200

  artists_spider:
    build:
      context: .
      dockerfile: scraper/Dockerfile
    depends_on:
      - mongodb
    command: sh -c "cd /app/scraper && pipenv run scrapy crawl artists -s SCRAPY_SETTINGS_MODULE=scraper.settings"
    volumes:
      - ./scraper/output:/app/output

  countries_spider:
    build:
      context: .
      dockerfile: scraper/Dockerfile
    depends_on:
      - mongodb
    command: sh -c "cd /app/scraper && pipenv run scrapy crawl countries -s SCRAPY_SETTINGS_MODULE=scraper.settings"
    volumes:
      - ./scraper/output:/app/output

  toplists_spider:
    build:
      context: .
      dockerfile: scraper/Dockerfile
    depends_on:
      - mongodb
    command: sh -c "cd /app/scraper && pipenv run scrapy crawl toplists -s SCRAPY_SETTINGS_MODULE=scraper.settings"
    volumes:
      - ./scraper/output:/app/output

  listeners_spider:
    build:
      context: .
      dockerfile: scraper/Dockerfile
    depends_on:
      - mongodb
    command: sh -c "cd /app/scraper && pipenv run scrapy crawl listeners -s SCRAPY_SETTINGS_MODULE=scraper.settings"
    volumes:
      - ./scraper/output:/app/output

  mongo_importer:
    build:
      context: ./MongoDB
      dockerfile: Dockerfile
    depends_on:
      - artists_spider
      - countries_spider
      - listeners_spider
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - MONGO_DATABASE=scrapy_data
    volumes:
      - ./scraper/output:/app/output
    command: sh -c "sleep 35 && python Mongo.py"

  elastic_importer:
    build:
      context: ./ElasticSearch
      dockerfile: Dockerfile
    depends_on:
      - elastic
      - mongo_importer
    environment:
      - ELASTICSEARCH_HOST=http://elastic:9200
    volumes:
      - ./scraper/output:/app/output
    command: sh -c "sleep 40 && python ElasticSearch.py"

volumes:
  mongodb_data:
